import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { EB_Garamond } from 'next/font/google';
import clsx from 'clsx';
import Providers from '@/app/Providers';
import './globals.css';

const ebGaramond = EB_Garamond({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang="en" className="h-full">
			<body className={clsx('h-full', ebGaramond.className)}>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
