export const TEMPLATES = [
	'**** ahead',
	'No **** ahead',
	'**** required ahead',
	'Be wary of ****',
	'Try ****',
	'Likely ****',
	'First off, ****',
	'Seek ****',
	'Still no ****...',
	'Why is it always ****?',
	'If only I had a ****...',
	`Didn't expect ****...`,
	'Visions of ****...',
	'Could this be a ****?',
	'Time for ****',
	'****, O ****',
	'Behold, ****!',
	'Offer ****',
	'Praise the ****!',
	'Let there be ****',
	'Ahh, ****...',
	'****',
	'****!',
	'****?',
	'****...',
];
